config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  resources :polls, :poll_questions, :poll_answers, only: %i[update destroy]

  scope '(:locale)', constraints: { locale: /ru|en|sv/ } do
    resources :polls, except: %i[update destroy], concerns: :check do
      member do
        post 'results' => :answer
        get 'results'
      end
    end
    resources :poll_questions, :poll_answers, only: %i[create edit], concerns: :check

    namespace :admin do
      resources :polls, only: %i[index show], concerns: :toggle do
        member do
          get 'users'
          post 'users' => :add_user, defaults: { format: :json }
          delete 'users/:user_id' => :remove_user, as: :user, defaults: { format: :json }
        end
      end
      resources :poll_questions, only: :show, concerns: %i[priority toggle]
      resources :poll_answers, only: :show, concerns: :priority
    end
  end
end

app/models/biovision/poll/application_record.rb
module Biovision
  module Poll
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/poll.rb
# frozen_string_literal: true

# Poll
# 
# Attributes:
#   active [boolean]
#   agent_id [Agent], optional
#   allow_comments [Boolean]
#   anonymous_votes [boolean]
#   comments_count [integer]
#   created_at [DateTime]
#   data [jsonb]
#   description [string], optional
#   end_date [date], optional
#   exclusive [boolean]
#   ip [inet]
#   language_id [Language], optional
#   name [string]
#   open_results [boolean]
#   poll_questions_count [integer]
#   pollable_id [integer], optional
#   pollable_type [string], optional
#   show_on_homepage [boolean]
#   simple_image_id [SimpleImage], optional
#   updated_at [DateTime]
#   user_id [User]
#   uuid [uuid]
#   visible [boolean]
class Poll < ApplicationRecord
  include Checkable
  include HasOwner
  include HasSimpleImage
  include HasUuid
  include Toggleable

  NAME_LIMIT        = 140
  DESCRIPTION_LIMIT = 255

  toggleable %i[active anonymous_votes open_results show_on_homepage exclusive visible]

  belongs_to :user
  belongs_to :agent, optional: true
  belongs_to :pollable, polymorphic: true, optional: true
  has_many :poll_questions, dependent: :delete_all
  has_many :poll_users, dependent: :delete_all

  validates_presence_of :name
  validates_length_of :description, maximum: DESCRIPTION_LIMIT
  validates_length_of :name, maximum: NAME_LIMIT

  scope :recent, -> { order('id desc') }
  scope :visible, -> { where(visible: true) }
  scope :active, -> { where('active = true and (end_date is null or (date(end_date) >= date(now())))') }
  scope :list_for_visitors, -> { active.visible.recent }
  scope :list_for_administration, -> { recent }

  # @param [Integer] page
  def self.page_for_administration(page = 1)
    list_for_administration.page(page)
  end

  # @param [Integer] page
  def self.page_for_visitors(page = 1)
    list_for_visitors.page(page)
  end

  def self.entity_parameters
    Poll.toggleable_attributes + %i[description end_date name simple_image_id]
  end

  # @param [User] user
  def editable_by?(user)
    return false if user.nil?

    owned_by?(user)
  end

  # @param [User] user
  def visible_to?(user)
    visible? || owned_by?(user)
  end

  # @param [User] user
  def votable_by?(user)
    return false if user.nil? || voted?(user)

    if exclusive?
      includes?(user)
    # elsif anonymous_votes?
    else
      true
    end
  end

  # @param [User] user
  def voted?(user)
    PollVote.where(poll_answer_id: answer_ids, user: user).exists?
  end

  # @param [User] user
  def show_results?(user)
    open_results? || editable_by?(user)
  end

  # @param [User] user
  def includes?(user)
    poll_users.owned_by(user).exists?
  end

  # @param [User] user
  def add_user(user)
    PollUser.create(poll: self, user: user)
  end

  # @param [User] user
  def remove_user(user)
    poll_users.owned_by(user).delete_all
  end

  def answer_ids
    PollAnswer.where(poll_question_id: poll_questions.pluck(:id)).pluck(:id)
  end

  # @param [User] user
  # @param [Hash] answers
  # @param [Hash] tracking
  # @param [String] slug
  def process_answers(user, answers, tracking, slug)
    return unless votable_by?(user)

    answers.each do |question_id, answer_ids|
      question = PollQuestion.find_by(id: question_id)
      next if question.nil? || question.poll_id != id

      if question.multiple_choice?
        answers = question.poll_answers.where(id: answer_ids)
      else
        answers = question.poll_answers.where(id: answer_ids.first)
      end

      answers.each do |answer|
        tracking[:slug] = slug
        answer.poll_votes.create(tracking)
      end
    end
  end
end

app/controllers/admin/polls_controller.rb
# frozen_string_literal: true

# Administrative part of handling polls
class Admin::PollsController < AdminController
  include ToggleableEntity
  
  before_action :set_entity, except: :index

  # get /admin/polls
  def index
    @collection = Poll.page_for_administration(current_page)
  end

  # get /admin/polls/:id
  def show
  end

  # get /admin/polls/:id/users
  def users
    @collection = @entity.poll_users.list_for_administration
  end

  # post /admin/polls/:id/users
  def add_user
    user = User.find_by(id: params[:user_id])

    @entity.add_user(user) unless user.nil?

    render :users
  end

  # delete /admin/polls/:id/users/:user_id
  def remove_user
    user = User.find_by(id: params[:user_id])

    @entity.remove_user(user) unless user.nil?

    render :users
  end

  private

  def component_class
    Biovision::Components::PollsComponent
  end

  def set_entity
    @entity = Poll.find_by(id: params[:id])
    handle_http_404('Cannot find poll') if @entity.nil?
  end
end

app/controllers/biovision/poll/application_controller.rb
module Biovision
  module Poll
    class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception
    end
  end
end

app/controllers/polls_controller.rb
# frozen_string_literal: true

# Displaying and editing polls
class PollsController < ApplicationController
  before_action :restrict_access, except: %i[index show results answer]
  before_action :set_entity, except: %i[check index new create]

  layout 'admin', except: %i[check index show results]

  # post /polls/check
  def check
    @entity = Poll.instance_for_check(params[:entity_id], entity_parameters)

    render 'shared/forms/check'
  end

  # get /polls
  def index
    @collection = Poll.page_for_visitors(current_page)
  end

  # get /polls/new
  def new
    @entity = Poll.new
  end

  # post /polls
  def create
    @entity = Poll.new(creation_parameters)
    if @entity.save
      form_processed_ok(admin_poll_path(id: @entity.id))
    else
      form_processed_with_error(:new)
    end
  end

  # get /polls/:id
  def show
    redirect_to polls_path unless @entity.visible_to?(current_user)
  end

  # get /polls/:id/edit
  def edit
  end

  # patch /polls/:id
  def update
    if @entity.update(entity_parameters)
      form_processed_ok(admin_poll_path(id: @entity.id))
    else
      form_processed_with_error(:edit)
    end
  end

  # delete /polls/:id
  def destroy
    flash[:notice] = t('.success') if @entity.destroy
    redirect_to(admin_polls_path)
  end

  # post /polls/:id/results
  def answer
    @entity.process_answers(current_user, params.require(:answer), owner_for_entity(true), visitor_slug)

    redirect_to results_poll_path(id: @entity.id)
  end

  # get /polls/:id/results
  def results
    redirect_to poll_path(id: @entity.id) unless @entity.show_results?(current_user)
  end

  protected

  def component_class
    Biovision::Components::PollsComponent
  end

  def restrict_access
    error = 'Managing polls is not allowed for current user'
    handle_http_401(error) unless component_handler.allow?
  end

  def set_entity
    @entity = Poll.find_by(id: params[:id])
    handle_http_404('Cannot find poll') if @entity.nil?
  end

  def entity_parameters
    params.require(:poll).permit(Poll.entity_parameters)
  end

  def creation_parameters
    entity_parameters.merge(owner_for_entity(true))
  end
end

app/helpers/biovision/poll/application_helper.rb
module Biovision
  module Poll
    module ApplicationHelper
    end
  end
end

app/helpers/polls_helper.rb
# frozen_string_literal: true

# Helper methods for polls component
module PollsHelper
  # @param [Poll] entity
  # @param [String] text
  # @param [Hash] options
  def admin_poll_link(entity, text = entity.name, options = {})
    link_to(text, admin_poll_path(id: entity.id), options)
  end

  # @param [PollQuestion] entity
  # @param [String] text
  # @param [Hash] options
  def admin_poll_question_link(entity, text = entity.text, options = {})
    link_to(text, admin_poll_question_path(id: entity.id), options)
  end

  # @param [PollAnswer] entity
  # @param [String] text
  # @param [Hash] options
  def admin_poll_answer_link(entity, text = entity.text, options = {})
    link_to(text, admin_poll_answer_path(id: entity.id), options)
  end

  # @param [Poll] entity
  # @param [String] text
  # @param [Hash] options
  def poll_link(entity, text = entity.name, options = {})
    link_to(text, poll_path(id: entity.id), options)
  end
end

app/views/admin/polls/_nav_item.html.erb
<div><%= link_to t('.text'), admin_polls_path %></div>
<div class="description"><%= t('.description') %></div>

app/views/admin/polls/index.html.erb
<% content_for :meta_title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <span><%= t('.nav_text') %></span>
<% end %>

<article>
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_path) %></li>
    <li><%= create_icon(new_poll_path) %></li>
  </ul>

  <%= paginate @collection %>
  <%=
    render(
        partial: 'shared/admin/list', locals: { collection: @collection }
    )
  %>
  <%= paginate @collection %>
</article>

app/views/admin/polls/show.html.erb
<% content_for :meta_title, t('.title', name: @entity.name) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.polls.index.nav_text'), admin_polls_path) %>
  <span><%= @entity.name %></span>
<% end %>

<article>
  <h1><%= @entity.name %></h1>

  <ul class="actions">
    <li><%= back_icon(admin_polls_path) %></li>
    <li><%= world_icon(poll_path(id: @entity.id)) %></li>
    <li><%= edit_icon(edit_poll_path(id: @entity.id)) %></li>
  </ul>

  <% if @entity.exclusive? %>
    <nav>
      <%=
        link_to(
            t('.allowed_users'),
            users_admin_poll_path(id: @entity.id),
            class: 'button-nav'
        )
      %>
    </nav>
  <% end %>

  <dl>
    <div>
      <dt><%= t('activerecord.attributes.poll.name') %></dt>
      <dd>
        <%= @entity.name %>
      </dd>
    </div>

    <% unless @entity.description.blank? %>
      <div>
        <dt><%= t('activerecord.attributes.poll.description') %></dt>
        <dd>
          <div class="text">
            <%= @entity.description %>
          </div>
        </dd>
      </div>
    <% end %>

    <% unless @entity.end_date.blank? %>
      <div>
        <dt><%= t('activerecord.attributes.poll.end_date') %></dt>
        <dd><%= time_tag(@entity.end_date) %></dd>
      </div>
    <% end %>

    <%= render partial: 'shared/entity/uuid', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/timestamps', locals: { entity: @entity } %>
  </dl>

  <%= render partial: 'admin/polls/entity/data', locals: { entity: @entity } %>

  <%=
    render(
        partial: 'shared/admin/toggleable',
        locals: {
            entity: @entity,
            url: toggle_admin_poll_path(id: @entity.id)
        }
    )
  %>

  <section>
    <h2><%= t(:poll_question_count, count: @entity.poll_questions_count) %></h2>

    <%=
      render(
          partial: 'shared/admin/list_with_priority',
          locals: { collection: @entity.poll_questions.ordered_by_priority }
      )
    %>
  </section>

  <% if @entity.poll_questions.count < 10 %>
    <section>
      <h2><%= t('poll_questions.new.heading') %></h2>

      <%=
        render(
            partial: 'poll_questions/form',
            locals: { entity: @entity.poll_questions.new }
        )
      %>
    </section>
  <% end %>
</article>

app/views/admin/polls/users.html.erb
<% content_for :meta_title, t('.title', name: @entity.name, page: current_page) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.polls.index.nav_text'), admin_polls_path) %>
  <%= admin_poll_link(@entity) %>
  <span><%= t('.heading') %></span>
<% end %>

<article>
  <h1><%= @entity.name %></h1>
  <h2><%= t('.heading') %></h2>

  <ul class="actions">
    <li><%= return_icon(admin_poll_path(id: @entity.id)) %></li>
  </ul>

  <div id="poll-allowed-users">
    <%= render partial: 'shared/admin/list', locals: { collection: @collection } %>
  </div>

  <%= render partial: 'admin/polls/entity/user_filter', locals: { entity: @entity } %>
</article>