config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  resources :polls, :poll_questions, :poll_answers, only: %i[update destroy]

  scope '(:locale)', constraints: { locale: /ru|en|sv/ } do
    resources :polls, except: %i[update destroy], concerns: :check do
      member do
        post 'results' => :answer
        get 'results'
      end
    end
    resources :poll_questions, :poll_answers, only: %i[create edit], concerns: :check

    namespace :admin do
      resources :polls, only: %i[index show], concerns: :toggle do
        member do
          get 'users'
          post 'users' => :add_user, defaults: { format: :json }
          delete 'users/:user_id' => :remove_user, as: :user, defaults: { format: :json }
        end
      end
      resources :poll_questions, only: :show, concerns: %i[priority toggle]
      resources :poll_answers, only: :show, concerns: :priority
    end
  end
end

app/models/poll_answer.rb
# frozen_string_literal: true

# Answer to poll question
# 
# Attributes:
#   created_at [DateTime]
#   data [jsonb]
#   poll_question_id [PollQuestion]
#   poll_votes_count [integer]
#   priority [integer]
#   simple_image_id [SimpleImage], optional
#   text [string]
#   updated_at [DateTime]
#   uuid [uuid]
class PollAnswer < ApplicationRecord
  include Checkable
  include HasSimpleImage
  include HasUuid
  include NestedPriority

  TEXT_LIMIT = 140

  belongs_to :poll_question, counter_cache: true
  has_many :poll_votes, dependent: :delete_all

  before_validation { self.text = text.to_s.strip }

  validates_presence_of :text
  validates_length_of :text, maximum: TEXT_LIMIT
  validates_uniqueness_of :text, scope: :poll_question_id

  scope :list_for_visitors, -> { ordered_by_priority }
  scope :list_for_administration, -> { ordered_by_priority }

  # @param [PollAnswer] entity
  def self.siblings(entity)
    where(poll_question_id: entity&.poll_question_id)
  end

  def self.entity_parameters
    %i[text simple_image_id]
  end

  def self.creation_parameters
    entity_parameters + %i[poll_question_id]
  end

  # @param [User] user
  def editable_by?(user)
    poll_question.poll.editable_by?(user)
  end

  def poll
    poll_question&.poll
  end

  def vote_percent
    poll_votes_count.to_f / poll_question.vote_count * 100
  end
end

app/controllers/admin/poll_answers_controller.rb
# frozen_string_literal: true

# Administrative part of hanlding poll answers
class Admin::PollAnswersController < AdminController
  include ToggleableEntity
  include EntityPriority

  before_action :set_entity

  # get /admin/poll_answers/:id
  def show
    @collection = @entity.poll_votes.page_for_administration(current_page)
  end

  private

  def component_class
    Biovision::Components::PollsComponent
  end

  def set_entity
    @entity = PollAnswer.find_by(id: params[:id])
    handle_http_404('Cannot find poll answer') if @entity.nil?
  end
end

app/controllers/poll_answers_controller.rb
# frozen_string_literal: true

# Editing poll answers
class PollAnswersController < AdminController
  before_action :set_entity, only: %i[edit update destroy]

  # post /poll_answers/check
  def check
    @entity = PollAnswer.instance_for_check(params[:entity_id], entity_parameters)

    render 'shared/forms/check'
  end

  # post /poll_answers
  def create
    @entity = PollAnswer.new(creation_parameters)
    if @entity.save
      form_processed_ok(admin_poll_question_path(id: @entity.poll_question_id))
    else
      form_processed_with_error(:new)
    end
  end

  # get /poll_answers/:id/edit
  def edit
  end

  # patch /poll_answers/:id
  def update
    if @entity.update(entity_parameters)
      form_processed_ok(admin_poll_question_path(id: @entity.poll_question_id))
    else
      form_processed_with_error(:edit)
    end
  end

  # delete /poll_answers/:id
  def destroy
    flash[:notice] = t('.success') if @entity.destroy
    redirect_to(admin_poll_question_path(id: @entity.poll_question_id))
  end

  protected

  def component_class
    Biovision::Components::PollsComponent
  end

  def set_entity
    @entity = PollAnswer.find_by(id: params[:id])
    handle_http_404('Cannot find poll answer') if @entity.nil?
  end

  def entity_parameters
    params.require(:poll_answer).permit(PollAnswer.entity_parameters)
  end

  def creation_parameters
    params.require(:poll_answer).permit(PollAnswer.creation_parameters)
  end
end

app/views/poll_answers/_form.html.erb
<% model_name = entity.class.to_s.underscore %>
<%=
  form_with(
      model: entity,
      html: {
          id: "#{model_name}-form",
          data: { check_url: check_poll_questions_path }
      }
  ) do |f|
%>
  <%= render partial: 'shared/list_of_errors', locals: { entity: entity } %>

  <dl class="fields">
    <% unless entity.id.nil? %>
      <div>
        <dt><%= t('activerecord.attributes.poll_answer.poll_question_id') %></dt>
        <dd><%= admin_poll_question_link(entity.poll_question) %></dd>
      </div>
    <% end %>

    <%= render partial: 'shared/forms/priority', locals: { f: f } %>

    <div>
      <dt><%= f.label :text %></dt>
      <dd>
        <%=
          f.text_field(
              :text,
              class: 'input-text',
              data: { check: :text },
              maxlength: PollAnswer::TEXT_LIMIT,
              placeholder: t('.placeholders.text'),
              required: true,
              size: nil
          )
        %>
        <div class="check-result-error" data-field="name"></div>
        <div class="guideline"><%= t('.guidelines.text') %></div>
      </dd>
    </div>
  </dl>

  <%= render 'shared/forms/state_container' %>

  <div class="buttons">
    <%= hidden_field_tag :entity_id, entity.id %>
    <%= f.hidden_field :poll_question_id if entity.id.nil? %>
    <%= f.button t(:save), class: 'button-save' %>
  </div>
<% end %>

app/views/poll_answers/_poll_answer.html.erb
<% question = poll_answer.poll_question %>
<div>
  <% qid = poll_answer.poll_question_id %>
  <% field_id = "poll_votes_#{qid}_#{poll_answer.id}" %>
  <% if question.multiple_choice? %>
    <%=
      check_box_tag(
          "answer[#{qid}][]",
          poll_answer.id,
          false,
          id: field_id
      )
    %>
  <% else %>
    <%=
      radio_button_tag(
          "answer[#{qid}][]",
          poll_answer.id,
          false,
          required: true,
          id: field_id
      )
    %>
  <% end %>
  <%= label_tag(field_id, poll_answer.text) %>
</div>

app/views/poll_answers/edit.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.polls.index.nav_text'), admin_polls_path) %>
  <%= admin_poll_link(@entity.poll) %>
  <%= admin_poll_question_link(@entity.poll_question) %>
  <%= admin_poll_answer_link(@entity) %>
  <span><%= t('.nav_text') %></span>
<% end %>

<article class="entity-page">
  <h1><%= t('.heading') %></h1>

  <ul class="actions">
    <li><%= return_icon(admin_poll_answer_path(id: @entity.id)) %></li>
    <li class="danger"><%= destroy_icon(@entity) %></li>
  </ul>

  <%= render partial: 'form', locals: { entity: @entity } %>
</article>

app/views/poll_answers/new.html.erb
<% content_for :meta_title, t('.title') %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.polls.index.nav_text'), admin_polls_path) %>
  <%= admin_poll_link(@entity.poll) unless @entity.poll.nil? %>
  <%= admin_poll_question_link(@entity.poll_question) unless @entity.poll_question.nil? %>
  <span><%= t('.nav_text') %></span>
<% end %>

<article>
  <h1><%= t('.title') %></h1>

  <% unless @entity.poll_id.nil? %>
    <ul class="actions">
      <li><%= return_icon(admin_poll_question_path(id: @entity.poll_question_id)) %></li>
    </ul>
  <% end %>

  <%= render partial: 'form', locals: { entity: @entity } %>
</article>