config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  concern :check do
    post :check, on: :collection, defaults: { format: :json }
  end

  concern :toggle do
    post :toggle, on: :member, defaults: { format: :json }
  end

  concern :priority do
    post :priority, on: :member, defaults: { format: :json }
  end

  resources :polls, :poll_questions, :poll_answers, only: %i[update destroy]

  scope '(:locale)', constraints: { locale: /ru|en|sv/ } do
    resources :polls, except: %i[update destroy], concerns: :check do
      member do
        post 'results' => :answer
        get 'results'
      end
    end
    resources :poll_questions, :poll_answers, only: %i[create edit], concerns: :check

    namespace :admin do
      resources :polls, only: %i[index show], concerns: :toggle do
        member do
          get 'users'
          post 'users' => :add_user, defaults: { format: :json }
          delete 'users/:user_id' => :remove_user, as: :user, defaults: { format: :json }
        end
      end
      resources :poll_questions, only: :show, concerns: %i[priority toggle]
      resources :poll_answers, only: :show, concerns: :priority
    end
  end
end

app/models/poll_question.rb
# frozen_string_literal: true

# Poll question
# 
# Attributes:
#   comment [string], optional
#   created_at [DateTime]
#   data [jsonb]
#   multiple_choice [boolean]
#   poll_answers_count [integer]
#   poll_id [Poll]
#   priority [integer]
#   simple_image_id [SimpleImage], optional
#   text [string]
#   updated_at [DateTime]
#   uuid [uuid]
class PollQuestion < ApplicationRecord
  include Checkable
  include HasSimpleImage
  include HasUuid
  include NestedPriority
  include Toggleable

  COMMENT_LIMIT = 255
  TEXT_LIMIT = 255

  toggleable :multiple_choice

  belongs_to :poll, counter_cache: true
  has_many :poll_answers, dependent: :delete_all

  before_validation { self.text = text.to_s.strip }

  validates_presence_of :text
  validates_length_of :text, maximum: TEXT_LIMIT
  validates_length_of :comment, maximum: COMMENT_LIMIT
  validates_uniqueness_of :text, scope: :poll_id

  scope :list_for_visitors, -> { ordered_by_priority }
  scope :list_for_administration, -> { ordered_by_priority }

  # @param [PollQuestion] entity
  def self.siblings(entity)
    where(poll_id: entity&.poll_id)
  end

  def self.entity_parameters
    PollQuestion.toggleable_attributes + %i[comment simple_image_id text]
  end

  def self.creation_parameters
    entity_parameters + %i[poll_id]
  end

  # @param [User] user
  def editable_by?(user)
    poll.editable_by?(user)
  end

  def vote_count
    poll_answers.pluck(:poll_votes_count).sum
  end
end

app/controllers/admin/poll_questions_controller.rb
# frozen_string_literal: true

# Administrative part for hanlding poll questions
class Admin::PollQuestionsController < AdminController
  include ToggleableEntity
  include EntityPriority

  before_action :set_entity

  # get /admin/poll_questions/:id
  def show
  end

  private

  def component_class
    Biovision::Components::PollsComponent
  end

  def set_entity
    @entity = PollQuestion.find_by(id: params[:id])
    handle_http_404('Cannot find poll question') if @entity.nil?
  end
end

app/controllers/poll_questions_controller.rb
# frozen_string_literal: true

# Managing poll questions
class PollQuestionsController < AdminController
  before_action :set_entity, only: %i[edit update destroy]

  # post /poll_questions/check
  def check
    @entity = PollQuestion.instance_for_check(params[:entity_id], entity_parameters)

    render 'shared/forms/check'
  end

  # post /poll_questions
  def create
    @entity = PollQuestion.new(creation_parameters)
    if @entity.save
      form_processed_ok(admin_poll_question_path(id: @entity.id))
    else
      form_processed_with_error(:new)
    end
  end

  # get /poll_questions/:id/edit
  def edit
  end

  # patch /poll_questions/:id
  def update
    if @entity.update(entity_parameters)
      form_processed_ok(admin_poll_question_path(id: @entity.id))
    else
      form_processed_with_error(:edit)
    end
  end

  # delete /poll_questions/:id
  def destroy
    flash[:notice] = t('.success') if @entity.destroy
    redirect_to(admin_poll_path(id: @entity.poll_id))
  end

  protected

  def component_class
    Biovision::Components::PollsComponent
  end

  def set_entity
    @entity = PollQuestion.find_by(id: params[:id])
    handle_http_404('Cannot find poll question') if @entity.nil?
  end

  def entity_parameters
    params.require(:poll_question).permit(PollQuestion.entity_parameters)
  end

  def creation_parameters
    params.require(:poll_question).permit(PollQuestion.creation_parameters)
  end
end

app/views/admin/poll_questions/show.html.erb
<% content_for :meta_title, t('.title', poll: @entity.poll.name, question: @entity.text) %>
<% content_for :breadcrumbs do %>
  <%= admin_biovision_component_link(component_handler.component) %>
  <%= link_to(t('admin.polls.index.nav_text'), admin_polls_path) %>
  <%= admin_poll_link(@entity.poll) %>
  <span><%= @entity.priority %>: <%= @entity.text %></span>
<% end %>

<article>
  <h1><%= @entity.text %></h1>

  <ul class="actions">
    <li><%= return_icon(admin_poll_path(id: @entity.poll_id)) %></li>
    <li><%= edit_icon(edit_poll_question_path(id: @entity.id)) %></li>
  </ul>

  <dl>
    <div>
      <dt><%= t('attributes.poll') %></dt>
      <dd>
        <%= admin_poll_link(@entity.poll) %>
      </dd>
    </div>

    <%= render partial: 'shared/entity/priority', locals: { entity: @entity } %>

    <div>
      <dt><%= t('activerecord.attributes.poll_question.text') %></dt>
      <dd>
        <div class="text"><%= @entity.text %></div>
      </dd>
    </div>

    <% unless @entity.comment.blank? %>
      <div>
        <dt><%= t('activerecord.attributes.poll_question.comment') %></dt>
        <dd>
          <div class="text"><%= @entity.comment %></div>
        </dd>
      </div>
    <% end %>

    <%= render partial: 'shared/entity/uuid', locals: { entity: @entity } %>
    <%= render partial: 'shared/entity/timestamps', locals: { entity: @entity } %>
  </dl>

  <%= render partial: 'admin/poll_questions/entity/data', locals: { entity: @entity } %>

  <%=
    render(
        partial: 'shared/admin/toggleable',
        locals: {
            entity: @entity,
            url: toggle_admin_poll_question_path(id: @entity.id)
        }
    )
  %>

  <section>
    <h2><%= t(:poll_answer_count, count: @entity.poll_answers_count) %></h2>

    <%=
      render(
          partial: 'shared/admin/list_with_priority',
          locals: { collection: @entity.poll_answers.ordered_by_priority }
      )
    %>
  </section>

  <% if @entity.poll_answers.count < 10 %>
    <section>
      <h2><%= t('poll_answers.new.heading') %></h2>

      <%= render partial: 'poll_answers/form', locals: { entity: @entity.poll_answers.new } %>
    </section>
  <% end %>
</article>